### ISSUE TITLE
远端图片显示问题

### ISSUE THREAD

**Issue by flovel** [zhitaocai/CocosCreator-Build-Encrypt#1]
在原生平台从远端获取的图片显示不出来，怎么解决？

**Comment by zhitaocai** [comment]
https://github.com/zhitaocai/CocosCreator-Build-Encrypt/blob/master/src/loaderplugin.js#L270

在这里，你可以先自行改动，逻辑如下：

如果item.url是网络图片地址，那么就不执行解密逻辑，直接使用原始加载图片逻辑

**Comment by zhitaocai** [comment]
https://github.com/zhitaocai/CocosCreator-Build-Encrypt/compare/dev...feature/split_remote_img

刚刚提交了一个 feature/splite_remote_img 的分支，你可以看下写法，我暂时没测试过

**Comment by flovel** [comment]
测试可以，谢谢！
